### Gradient Descent

In [17]:
# Implement gradient descent here

import numpy as np

def f(x,y):
    # Function definition here
    return (1-x)**2 + 100*(y-x**2)**2

def gradf(x,y):
    # Gradient definition here
    return np.array([2*(x-1) + 200*(y - x**2)*(-2*x), 200*(y-x**2)])

def hessian(x,y):
    # Gradient definition here
    return np.array([[2+200*(6*x**2 - 2*y), -400*x],
                     [-400*x, 200]])

def exactStep(f,df,step,x0):
    X = x0
    for i in range(0,1000):
        X_new = X - step*gradf(X[0], X[1])
        if np.linalg.norm(df(X_new[0],X_new[1])) <= 1e-6:
            return("Root at: {}".format(X_new))
        X = X_new
        print(X)
    return("Root not reached. Terminated at {}.".format(X))

def bisectionSearch(f,df,step,x0):
    X = x0
    for i in range(0,1000):
        if np.linalg.norm(df(X[0],X[1])) <= 1e-6:
            return("Root at: {}".format(X))
        elif np.linalg.norm(df(X[0],X[1])) < 0:
            X = X+step
        elif np.linalg.norm(df(X[0],X[1])) > 0:
            X = X - step*gradf(X[0], X[1])
        print(X)
    return("Root not reached. Terminated at {}.".format(X))

def newtonStep(f,df,step,x0):
    X = x0
    for i in range(0,1000):
        H_inv = np.linalg.inv(hessian(X[0], X[1]))
        grad=gradf(X[0], X[1])
        X_new = X - np.matmul(H_inv,grad) #step*gradf(X[0], X[1])
        print(X_new)
        if np.linalg.norm(np.array(X) - np.array(X_new)) <= 1e-6:
            return("Root at: {}".format(X_new))
        X = X_new
    return("Root not reached. Terminated at {}.".format(X))

In [18]:
X0 = np.array([-0.8,1]) # Starting state
step = 0.001
newtonStep(f,gradf,step,X0)

(2,)
[-0.82535211  0.68056338]
(2,)
[ 0.79208505 -1.98870424]
(2,)
[0.79248166 0.62802703]
(2,)
[0.99999347 0.95692579]
(2,)
[0.99999415 0.9999883 ]
(2,)
[1. 1.]
(2,)
[1. 1.]


'Root at: [1. 1.]'

### Newton Step 

In [54]:
def alpha(f, df, d, X):
    r = d - gradf(*X) 
    return((r.dot(r))/(d.dot(f(*d))))

In [62]:
def conjGradient(f,df,x0,n):
    X = x0
    # take negative gradient as first direction vector
    d = [None for _ in range(n+1)]
    d[0] = np.array(-gradf(X[0],X[1]))
    alphas = [None for _ in range(n+1)]
    for i in range(n):
        # remainder = b - Ax
        r = d[i] - gradf(*X) 

        a = (r.dot(r))/(d[i].dot(f(*d[i])))
        alphas[i] = a

        X_new = X + a.dot(d[i])

        r_new = r.dot(f(*d[i]))

        beta = (r_new.dot(r_new))/(r.dot(r))

        d[i+1] = r_new + beta*(d[i])
    r_n = d[n] - gradf(*X) 
    alphas[n] = (r.dot(r))/(d[n].dot(f(*d[n])))
    return(d, alphas)
        

In [63]:
newtonStep(f,gradf,np.array([-0.8,1]),2)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in double_scalars
  import sys


([array([-111.6,  -72. ]),
  array([-2.74784473e+22, -1.77280305e+22]),
  array([-8.93160882e+205, -5.76232827e+205])],
 [array([-4.02897828e-08, -6.24491634e-08]),
  array([-6.82587252e-70, -1.05801024e-69]),
  array([-0., -0.])])