In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cp

# Note: Remember to mention convexity in the report, why the optimization function is not a convex function

In [31]:
cp.multiply(c,x)

Expression(AFFINE, UNKNOWN, (10, 4))

In [40]:
m = 4   # Number of warehouse
n = 10  # Number of demands

f = np.random.randint(100,size=m)       # Fixed cost for each warehouse
c = np.random.randint(100,size=(n,m))   # Transportation cost for each warehouse to the respective customer
d = np.random.randint(50,size=n)       # Demands
w = np.random.randint(100,size=m)       # Capacity of each warehouse

# Strange error: I had to explicitly declare shape=(4,10). Cannot use shape=(m,n)
x = cp.Variable(shape=(n,m))
y = cp.Variable(m,boolean=True)

fixed_cost = sum(cp.multiply(f,y))
transport_cost = sum(sum(cp.multiply(c,x)))
total_cost = fixed_cost + transport_cost
obj = cp.Minimize(total_cost)
constraints = []
for i in range(n):
    for j in range(m):
        constraints.extend([x[i][j] <= d[i]*y[j]])
        constraints.extend([x[i][j] >= 0])
        
# Goods can only be shipped if the warehouse is opened
constraints.extend([cp.sum(x,axis=0) - y*cp.sum(d) <= 0])
# Service provided by each warehouse must not exceed its capacity
constraints.extend([sum(x[:,j]) <= w[j]*y[j] for j in range(4)])
'''
# Every demand must be satisfied
constraints = [cp.sum(x,axis=1) <= d, cp.sum(x,axis=1) >= d]      # ?!?!
# Goods can only be shipped if the warehouse is opened
constraints.extend([cp.sum(x,axis=0) - y*cp.sum(d) <= 0])
# Service provided by each warehouse must not exceed its capacity
constraints.extend([sum(x[:,j]) <= w[j]*y[j] for j in range(4)])
'''
prob = cp.Problem(obj,constraints)
sol = prob.solve(solver="ECOS_BB")
print(sol)
print(x.value)
print(y.value)

1.1653995224822358e-11
[[ 5.36198292e-15 -8.35263250e-15 -6.64976194e-15 -5.23764003e-15]
 [-8.45774318e-16 -8.97515967e-15 -1.26346216e-15  1.16695420e-14]
 [ 1.06840444e-15  6.10731198e-14 -1.15046045e-14  1.84254609e-13]
 [-2.40790857e-15  4.97825674e-15 -1.40409834e-15  7.66630152e-14]
 [-1.61605580e-14 -9.44075339e-15 -1.03364536e-14 -7.69190580e-15]
 [ 3.34861235e-16 -6.55382902e-15 -7.62785164e-15 -1.01001852e-14]
 [-1.06088840e-14 -1.09670742e-14 -1.11791000e-14 -7.87265382e-15]
 [-5.10590350e-16 -2.15951795e-15 -8.88825241e-15 -1.02807953e-14]
 [-9.00533979e-16 -1.05235179e-14 -5.96015953e-15 -7.07732461e-15]
 [-3.83334565e-15 -4.94638174e-15 -7.16634416e-15 -4.89887298e-15]]
[7.72509251e-12 2.27064870e-14 9.73658085e-14 3.80462565e-13]
